path: ../dataset

train: dataset/train/images
val: dataset/valid/images
test: dataset/test/images

nc: 2
names: ['cavity', 'tooth']

roboflow:
  workspace: yolo-v8-training
  project: tooth-caries-3
  version: 2
  license: CC BY 4.0
  url: https://universe.roboflow.com/yolo-v8-training/tooth-caries-3/dataset/2
